### ISSUE TITLE
Add link to hosted version

### ISSUE THREAD

**Issue by owencm** [aurelia/app-ux-showcase#4]
I wanted to take a look quickly to get a sense but don't see any way to try without hosting myself.

Can you host a version and link to it from the readme?

Thanks!

**Comment by EisenbergEffect** [comment]
We're going to get something up in a bit.

**Comment by inhuman-programmer** [comment]
+1  that would be useful

**Comment by landofjoe** [comment]
Any progress on this?  I want to explore it and possibly use it, but I don't have the time to pull down the live showcase and try to build it and get it running.  Just my $0.02, but I think having live demo for things like this is absolutely critical for mass adoption.

**Comment by mttmccb** [comment]
Any reason not to use github pages?

**Comment by khuongduybui** [comment]
It needs to be built anyway. Using Github pages, you would have to manually build and upload.

**Comment by peterennis** [comment]
Also looking to review some online demo. I am not ready to build it myself just to see if I want to consider using the tool.

**Comment by okezieokpara** [comment]
I was finally able to get this up and running if you have any issues, I can try help out.
I should host it publicly soon.

**Comment by albuumg** [comment]
I tried it locally but I'm getting this error: 
Unhandled rejection Error: Load timeout for modules: template-registry-entry!aurelia-ux/chip-input/ux-chip-input.html,template-registry-entry!aurelia-ux/chip-input/ux-chip.html,template-registry-entry!aurelia-ux/chip-input/ux-tag.html,text!aurelia-ux/chip-input/ux-chip-input.html,text!aurelia-ux/chip-input/ux-chip.html,text!aurelia-ux/chip-input/ux-tag.html
http://requirejs.org/docs/errors.html#timeout
    at Error (native)
    at F (http://localhost:9000/scripts/vendor-bundle.js:3784:290)
    at H (http://localhost:9000/scripts/vendor-bundle.js:3790:56)
    at http://localhost:9000/scripts/vendor-bundle.js:3790:227
From previous event:
    at DefaultLoader._import (http://localhost:9000/scripts/vendor-bundle.js:11616:14)
    at DefaultLoader.loadTemplate (http://localhost:9000/scripts/vendor-bundle.js:11583:19)
    at ensureRegistryEntry (http://localhost:9000/scripts/vendor-bundle.js:19579:19)
    at ViewEngine.loadViewFactory (http://localhost:9000/scripts/vendor-bundle.js:19647:14)
    at ConventionalViewStrategy.loadViewFactory (http://localhost:9000/scripts/vendor-bundle.js:17041:25)
    at HtmlBehaviorResource.load (http://localhost:9000/scripts/vendor-bundle.js:20420:29)
    at ResourceDescription.load (http://localhost:9000/scripts/vendor-bundle.js:19466:28)
    at ResourceModule.load (http://localhost:9000/scripts/vendor-bundle.js:19408:25)
    at http://localhost:9000/scripts/vendor-bundle.js:19776:43
From previous event:
    at ViewEngine.importViewResources (http://localhost:9000/scripts/vendor-bundle.js:19745:52)
    at http://localhost:9000/scripts/vendor-bundle.js:10702:25
From previous event:
    at loadResources (http://localhost:9000/scripts/vendor-bundle.js:10693:9)
    at http://localhost:9000/scripts/vendor-bundle.js:10770:16
    at next (http://localhost:9000/scripts/vendor-bundle.js:10650:32)
    at runTasks (http://localhost:9000/scripts/vendor-bundle.js:10656:12)
    at http://localhost:9000/scripts/vendor-bundle.js:10936:18
From previous event:
    at http://localhost:9000/scripts/vendor-bundle.js:10935:23
From previous event:
    at FrameworkConfiguration.apply (http://localhost:9000/scripts/vendor-bundle.js:10920:44)
    at Aurelia.start (http://localhost:9000/scripts/vendor-bundle.js:10536:39)
    at Object.configure (http://localhost:9000/scripts/app-bundle.js:111:17)
    at http://localhost:9000/scripts/vendor-bundle.js:9599:22
From previous event:
    at config (http://localhost:9000/scripts/vendor-bundle.js:9594:48)
    at handleApp (http://localhost:9000/scripts/vendor-bundle.js:9585:12)
    at http://localhost:9000/scripts/vendor-bundle.js:9618:13
From previous event:
    at http://localhost:9000/scripts/vendor-bundle.js:9616:40
From previous event:
    at http://localhost:9000/scripts/vendor-bundle.js:9615:29
From previous event:
    at run (http://localhost:9000/scripts/vendor-bundle.js:9611:26)
    at Object.<anonymous> (http://localhost:9000/scripts/vendor-bundle.js:9638:3)
    at Object.execCb (http://localhost:9000/scripts/vendor-bundle.js:3806:299)
    at Object.check (http://localhost:9000/scripts/vendor-bundle.js:3795:50)
    at Object.enable (http://localhost:9000/scripts/vendor-bundle.js:3800:58)
    at Object.enable (http://localhost:9000/scripts/vendor-bundle.js:3804:433)
    at Object.<anonymous> (http://localhost:9000/scripts/vendor-bundle.js:3799:436)
    at http://localhost:9000/scripts/vendor-bundle.js:3784:140
    at y (http://localhost:9000/scripts/vendor-bundle.js:3783:207)
    at Object.enable (http://localhost:9000/scripts/vendor-bundle.js:3798:469)
    at Object.init (http://localhost:9000/scripts/vendor-bundle.js:3793:154)
    at http://localhost:9000/scripts/vendor-bundle.js:3803:308

**Comment by ZHollingshead** [comment]
@albuumg this is likely due to an update to the library. My latest PR will solve this but in the meantime you can fix this issue by going to the Aurelia.json file in the Aurelia_Project folder and replacing the aurelia entry with this.

``` json
      {
        "name": "aurelia-ux",
        "path": "../node_modules/aurelia-ux/dist/amd",
        "main": "index",
        "resources": [
          "./button/ux-button.html",
          "./button/ux-button-theme.css",
          "./input/ux-input.html",
          "./input/ux-input-theme.css",
          "./input-info/ux-input-info.html",
          "./input-info/ux-input-info-theme.css",
          "./textarea/ux-textarea.html",
          "./textarea/ux-textarea-theme.css",
          "./form/ux-form.html",
          "./form/ux-form-theme.css",
          "./form/ux-field.html",
          "./form/ux-field-theme.css",
          "./chip-input/ux-chip-input.html",
          "./chip-input/ux-chip-input-theme.css",
          "./chip-input/ux-chip.html",
          "./chip-input/ux-chip-theme.css",
          "./chip-input/ux-tag.html",
          "./chip-input/ux-tag-theme.css"
        ]
      }
```

**Comment by jeffgrann** [comment]
What's going on with the hosted showcase? I would think it would exist by now.

**Comment by alexisargyris** [comment]
Well, it certainly would be nice to be able to see something without having to do anything, but it really took less than five minutes to set it up locally.

**Comment by jeffgrann** [comment]
@alexisargyris I'm thinking about developers who are looking into using Aurelia and want to see the current state of Aurelia UX. It should be as easy as possible for them.

**Comment by ZHollingshead** [comment]
@jeffgrann the plan is to add this to the new developer Hub when it is ready. See #19.

@EisenbergEffect is working on that.

**Comment by EisenbergEffect** [comment]
It's coming as part of the new hub....

**Comment by veikkoeeva** [comment]
Stumbled upon this while searching for something to see. Does someone know sources to see even some of the components?

**Comment by Alexander-Taran** [comment]
can we set up a deployed to firebase app?

**Comment by brianjlacy** [comment]
The demo link provided does not work for me. Just a blank screen.

**Comment by veikkoeeva** [comment]
The link https://aux-demo.firebaseapp.com/getting-started seems to be working.

**Comment by veikkoeeva** [comment]
I think the showcase link ought to be shown at https://github.com/aurelia/app-ux-showcase, by the way. It's plenty of digging to get it from here. :)
