### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by johnmanko** [aurelia/app-ux-showcase#45]
**I'm submitting a bug report**

* **Library Version:**
0.1.0

**Please tell us about your environment:**
* **Operating System:**
Ubuntu Linux 20.10

* **Node Version:**
14.15.1

* **NPM Version:**
6.14.11

* **JSPM OR Webpack AND Version**
webpack 4.6.0

* **Browser:**
Chrome 87.0.4280.141

* **Language:**
TypeScript 3.1.3

**Current behavior:**

`npm install` fails:

```
3628 silly resolveWithNewModule webpack-dev-server@3.11.2 checking installable status
3629 silly fetchPackageMetaData error for gulp@github:gulpjs/gulp#4.0 Command failed: git checkout 4.0
3629 silly fetchPackageMetaData error: pathspec '4.0' did not match any file(s) known to git
3630 timing stage:rollbackFailedOptional Completed in 0ms
3631 timing stage:runTopLevelLifecycles Completed in 39783ms
3632 silly saveTree aureliaux-showcase@0.1.0
3632 silly saveTree ├─┬ @aurelia-ux/components@0.11.1
3632 silly saveTree │ ├─┬ @aurelia-ux/button@0.11.1
3632 silly saveTree │ │ ├─┬ @aurelia-ux/core@0.11.1
3632 silly saveTree │ │ │ ├─┬ aurelia-binding@2.5.4
3632 silly saveTree │ │ │ │ ├── aurelia-logging@1.5.2
3632 silly saveTree │ │ │ │ ├─┬ aurelia-metadata@1.0.7
3632 silly saveTree │ │ │ │ │ └── aurelia-pal@1.8.2
3632 silly saveTree │ │ │ │ ├── aurelia-pal@1.8.2
3632 silly saveTree │ │ │ │ └── aurelia-task-queue@1.3.3
3632 silly saveTree │ │ │ ├─┬ aurelia-framework@1.3.1
3632 silly saveTree │ │ │ │ ├── aurelia-dependency-injection@1.5.2
3632 silly saveTree │ │ │ │ ├─┬ aurelia-loader@1.0.2
3632 silly saveTree │ │ │ │ │ └── aurelia-path@1.1.5
3632 silly saveTree │ │ │ │ ├── aurelia-path@1.1.5
3632 silly saveTree │ │ │ │ └── aurelia-templating@1.10.4
3632 silly saveTree │ │ │ └── aurelia-templating-resources@1.13.1
3632 silly saveTree │ │ └── aurelia-framework@1.3.1
3632 silly saveTree │ ├── @aurelia-ux/card@0.11.1
3632 silly saveTree │ ├── @aurelia-ux/checkbox@0.11.1
3632 silly saveTree │ ├── @aurelia-ux/chip-input@0.11.1
3632 silly saveTree │ ├── @aurelia-ux/core@0.11.1
3632 silly saveTree │ ├─┬ @aurelia-ux/datepicker@0.11.1
3632 silly saveTree │ │ └── moment@2.29.1
3632 silly saveTree │ ├── @aurelia-ux/form@0.11.1
3632 silly saveTree │ ├── @aurelia-ux/grid@0.11.1
3632 silly saveTree │ ├── @aurelia-ux/input-info@0.11.1
3632 silly saveTree │ ├── @aurelia-ux/input@0.11.1
3632 silly saveTree │ ├── @aurelia-ux/list@0.11.1
3632 silly saveTree │ ├── @aurelia-ux/radio@0.11.1
3632 silly saveTree │ ├── @aurelia-ux/select@0.11.1
3632 silly saveTree │ ├── @aurelia-ux/switch@0.11.1
3632 silly saveTree │ ├── @aurelia-ux/textarea@0.11.1
3632 silly saveTree │ └── aurelia-framework@1.3.1
3632 silly saveTree ├── @aurelia-ux/core@0.11.1
3632 silly saveTree ├── @aurelia-ux/icons@0.11.1
3632 silly saveTree ├── @types/lodash@4.14.168
3632 silly saveTree ├── @types/node@6.14.13
3632 silly saveTree ├── @types/webpack@3.8.20
3632 silly saveTree ├── aurelia-animator-css@1.0.4
3632 silly saveTree ├── aurelia-binding@2.5.4
3632 silly saveTree ├─┬ aurelia-bootstrapper@2.3.3
3632 silly saveTree │ ├── aurelia-event-aggregator@1.0.3
3632 silly saveTree │ ├─┬ aurelia-history-browser@1.4.0
3632 silly saveTree │ │ └── aurelia-history@1.2.1
3632 silly saveTree │ ├── aurelia-history@1.2.1
3632 silly saveTree │ ├── aurelia-loader-default@1.2.1
3632 silly saveTree │ ├── aurelia-logging-console@1.1.1
3632 silly saveTree │ ├── aurelia-pal-browser@1.8.1
3632 silly saveTree │ ├── aurelia-polyfills@1.3.4
3632 silly saveTree │ ├─┬ aurelia-router@1.7.1
3632 silly saveTree │ │ └── aurelia-route-recognizer@1.3.2
3632 silly saveTree │ ├── aurelia-templating-binding@1.5.3
3632 silly saveTree │ └── aurelia-templating-router@1.4.0
3632 silly saveTree ├── aurelia-cli@0.33.1
3632 silly saveTree ├── aurelia-polyfills@1.3.4
3632 silly saveTree ├── aurelia-templating-resources@1.13.1
3632 silly saveTree ├── aurelia-testing@1.0.0
3632 silly saveTree ├─┬ aurelia-tools@2.0.0
3632 silly saveTree │ └── through2@2.0.5
3632 silly saveTree ├── aurelia-validation@1.6.0
3632 silly saveTree ├─┬ aurelia-webpack-plugin@3.0.0
3632 silly saveTree │ ├── html-loader@0.5.5
3632 silly saveTree │ └── minimatch@3.0.4
3632 silly saveTree ├── bluebird@3.7.2
3632 silly saveTree ├── copy-webpack-plugin@4.6.0
3632 silly saveTree ├── css-loader@0.28.11
3632 silly saveTree ├── del@3.0.0
3632 silly saveTree ├── expose-loader@0.7.5
3632 silly saveTree ├── file-loader@1.1.11
3632 silly saveTree ├── gulp-rename@1.4.0
3632 silly saveTree ├── html-loader@0.5.5
3632 silly saveTree ├── html-webpack-plugin@3.2.0
3632 silly saveTree ├── istanbul-instrumenter-loader@2.0.0
3632 silly saveTree ├── json-loader@0.5.7
3632 silly saveTree ├── minimatch@3.0.4
3632 silly saveTree ├── nps-utils@1.2.0
3632 silly saveTree ├── nps@5.10.0
3632 silly saveTree ├── opn@5.5.0
3632 silly saveTree ├─┬ prismjs@1.23.0
3632 silly saveTree │ └─┬ clipboard@2.0.6
3632 silly saveTree │   ├─┬ good-listener@1.2.2
3632 silly saveTree │   │ └── delegate@3.2.0
3632 silly saveTree │   ├── select@1.1.2
3632 silly saveTree │   └── tiny-emitter@2.1.0
3632 silly saveTree ├── style-loader@0.18.2
3632 silly saveTree ├── through2@2.0.5
3632 silly saveTree ├── ts-loader@4.5.0
3632 silly saveTree ├── ts-node@3.3.0
3632 silly saveTree ├── typescript@3.9.7
3632 silly saveTree ├── uglify-js@3.12.4
3632 silly saveTree ├── url-loader@1.1.2
3632 silly saveTree ├── vinyl-fs@2.4.4
3632 silly saveTree ├── webpack-cli@2.1.5
3632 silly saveTree ├── webpack-dev-server@3.11.2
3632 silly saveTree └── webpack@4.46.0
3633 verbose stack Error: Command failed: git checkout 4.0
3633 verbose stack error: pathspec '4.0' did not match any file(s) known to git
3633 verbose stack
3633 verbose stack     at ChildProcess.exithandler (child_process.js:308:12)
3633 verbose stack     at ChildProcess.emit (events.js:315:20)
3633 verbose stack     at maybeClose (internal/child_process.js:1048:16)
3633 verbose stack     at Socket.<anonymous> (internal/child_process.js:439:11)
3633 verbose stack     at Socket.emit (events.js:315:20)
3633 verbose stack     at Pipe.<anonymous> (net.js:673:12)
3634 verbose cwd aurelia/app-ux-showcase
3635 verbose Linux 5.8.0-36-generic
3636 verbose argv "bin/node" "bin/npm" "install"
3637 verbose node v14.15.1
3638 verbose npm  v6.14.11
3639 error code 1
3640 error Command failed: git checkout 4.0
3640 error error: pathspec '4.0' did not match any file(s) known to git
3641 verbose exit [ 1, true ]
```

**Expected/desired behavior:**
Successful install of node modules.

* **What is the motivation / use case for changing the behavior?**
Fix this project to work.

**Comment by dkent600** [comment]
same here

**Comment by dkent600** [comment]
This suggestion eliminates the problem:  https://github.com/madoublet/respond/issues/598#issuecomment-457818753

**Comment by Alexander-Taran** [comment]
Would you like to provide a pull request for it @dkent600 ?

**Comment by dkent600** [comment]
> Would you like to provide a pull request for it @dkent600 ?

Maybe, in the next month or two I may have time.
